NumPy Arrays

In [1]:
my_list=[1,2,3]


In [2]:
import numpy as np

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.63473957, 0.04140668, 0.51570538, 0.29728442, 0.76025805])

In [24]:
np.random.rand(3,4)

array([[0.95154772, 0.62806354, 0.14878702, 0.77677533],
       [0.18324017, 0.36480994, 0.72998736, 0.43738673],
       [0.68958748, 0.03216195, 0.24878443, 0.00251526]])

In [29]:
np.random.randn(4,4)

array([[ 0.33195215,  0.44208273,  1.32808622, -0.31539014],
       [-1.41550628,  0.38374696, -0.65021164, -0.66468273],
       [-0.05403223,  0.04459269,  0.8927912 , -1.92687593],
       [-1.32270457, -0.34401626, -0.91913638,  0.32386376]])

In [28]:
np.random.randn(2,2)

array([[0.75527339, 0.40891426],
       [0.65459986, 1.28965502]])

In [30]:
np.random.rand(2)

array([0.69099093, 0.31475546])

In [37]:
np.random.randint(1,100)

47

In [38]:
np.random.randint(1,100,10)

array([ 3, 15, 42,  5, 92, 36,  2, 47, 37, 64])

In [78]:
arr=np.arange(25)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr=np.random.randint(0,50,10)

In [42]:
ranarr

array([11, 20,  6, 43,  4, 28,  8, 37,  0, 41])

In [45]:
# arr=np.arange(12)
# arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
ranarr

array([11, 20,  6, 43,  4, 28,  8, 37,  0, 41])

In [47]:
ranarr.max()

43

In [48]:
ranarr.min()

0

In [49]:
ranarr

array([11, 20,  6, 43,  4, 28,  8, 37,  0, 41])

In [50]:
ranarr.argmax()

3

In [51]:
ranarr.argmin()

8

In [80]:
arr = arr.reshape(5,5)

In [81]:
arr.shape

(5, 5)

In [82]:
arr.dtype

dtype('int32')

                from numpy.random import randint

In [85]:
from numpy.random import randint

In [84]:
randint(2,10)

5