In [1]:
import numpy as np
arr=np.array(23)
print(arr)
arr

23


array(23)

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as no
arr=np.array([[[1,2,3],[4,5,6]],[[9,2,3],[4,5,6]]])
print(arr)
arr

[[[1 2 3]
  [4 5 6]]

 [[9 2 3]
  [4 5 6]]]


array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 2, 3],
        [4, 5, 6]]])

In [9]:
2+5


7

In [10]:
import numpy as no
arr=np.array([[[1,2,3],[4,5,6]],[[9,2,3],[4,5,6]]])
print(arr.ndim)

3


In [13]:
arr=np.array(23)
print(arr.ndim)
arr.ndim

0


0

In [15]:
arr=np.array([1,2,3,4,5])
print(arr.ndim)
arr.ndim

1


1

In [16]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr.ndim

[[1 2 3]
 [4 5 6]]


2

In [17]:
import numpy as np
arr=np.array([1,2,3],ndmin=5)
arr

array([[[[[1, 2, 3]]]]])

In [19]:
import numpy as np
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)

[1 2 3]


In [25]:
import numpy as np
arr=np.array([2.3,4.5,6.7,8.9])
newarr=arr.astype('i')
secondarr=newarr.astype('S')
print(newarr)
print(secondarr)
thirdarr=secondarr.astype(bool)
thirdarr
print(thirdarr)

[2 4 6 8]
[b'2' b'4' b'6' b'8']
[ True  True  True  True]


In [27]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(x)
print(arr)

[1 2 3 4 5]
[42  2  3  4  5]


In [29]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(x)
print(arr)


[42  2  3  4  5]
[42  2  3  4  5]


In [30]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]
