In [1]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.__version__)

2.1.3


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arr= np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
 import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [19]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
arr[0]

[1 2 3 4 5]
<class 'numpy.ndarray'>


np.int64(1)

In [20]:
type(arr)

numpy.ndarray

    #Numpy Array indexing 


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr[0]
print(arr[0])

1


In [3]:
arr[1]

np.int64(2)

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[3])


7


    #Access 2-D Arrays

In [6]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


In [7]:
print(arr[1,4])

10


    #Access 3-D Arrays

In [8]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[0,1,2]

np.int64(6)

    #Negative Indexing

In [11]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


    ##Slicing arrays

In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [13]:
print(arr[4:0])

[]


In [14]:
print(arr[4:])

[5 6 7]


In [15]:
print(arr[:4])

[1 2 3 4]


    ##Negative Slicing

In [16]:
print(arr[-3:-1])

[5 6]


In [18]:
print(arr[0:-1])

[1 2 3 4 5 6]


In [20]:
print(arr[-1])

7


    #step Slicing

In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [23]:
print(arr[::2])

[1 3 5 7]


    ##Slicing 2-D Arrays

In [25]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [26]:
print(arr[0:2,2])

[3 8]


In [3]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [7]:
import numpy as np
arr=np.array([10,15,20,25,30,35,40])
print(arr[1:4:2])
print(arr[0:5:2])
print(arr[0:4:])

[15 25]
[10 20 30]
[10 15 20 25]


In [8]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr
[::2]
)

[10 20 30 40]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.dtype)

int64


In [13]:
import numpy as np
arr=np.array(['Anoop','Anand','Abhay'])
print(arr.dtype)

<U5


                                            #Numpy Practice from W3S question

In [8]:
import numpy as np
print(np.__version__)

2.1.3


In [10]:
import numpy as np
arr=np.array(45)
print(arr)

45


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [19]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,6,7]])
arrp=np.array(([1,2,3,4],[5,6,6,7]))
print(arr)
print(arrp)

[[1 2 3 4]
 [5 6 6 7]]
[[1 2 3 4]
 [5 6 6 7]]


In [27]:
import numpy as np
arr=np.array([[[1,2,3,0],[4,5,6,9]],[[3,2,1,8],[7,8,9,8]]])
print(arr)

[[[1 2 3 0]
  [4 5 6 9]]

 [[3 2 1 8]
  [7 8 9 8]]]


In [26]:
import numpy as np
a=np.array(45)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3,4],[5,6,6,7]])
# d=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[7,8,9]]])
d=np.array([[[1,2,3,0],[4,5,6,9]],[[3,2,1,8],[7,8,9,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [34]:
import numpy as np
arr5=np.array([1,2,3,4],ndmin=5)
arr4=np.array([1,2,3,4],ndmin=4)
arr3=np.array([1,2,3,4],ndmin=3)
arr2=np.array([1,2,3,4],ndmin=2)
arr1=np.array([1,2,3,4],ndmin=1)
print(arr1)
print(arr1.ndim)
print(arr2)
print(arr2.ndim)
print(arr3)
print(arr3.ndim)
print(arr4)
print(arr4.ndim)
print(arr5)
print(arr5.ndim)

[1 2 3 4]
1
[[1 2 3 4]]
2
[[[1 2 3 4]]]
3
[[[[1 2 3 4]]]]
4
[[[[[1 2 3 4]]]]]
5


In [35]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [36]:
# import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


In [37]:
print(arr[1,4])

10


In [39]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [40]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


In [41]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [42]:
print(arr[4:])

[5 6 7]


In [43]:
print(arr[:4])

[1 2 3 4]


In [45]:
print(arr[-3:-1])

[5 6]


In [46]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [47]:
arr[::2]

array([1, 3, 5, 7])

In [48]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [49]:
arr[0:2,2]

array([3, 8])

In [55]:
arr[0:2,1:4]
# print(len([1]))
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [58]:
arr=np.array([1,2,3,4])
print(arr.dtype)
arr.dtype

int64


dtype('int64')

In [59]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)

[b'1' b'2' b'3' b'4']


In [60]:
print(arr.dtype)

|S1


                                ##Numpy Practice from w3s day-2

In [1]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,1:4]

array([7, 8, 9])

In [2]:
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [3]:
arr[0:2,2]

array([3, 8])